import type { DirectoryLocale } from "@/lib/directory-i18n";

// BusinessCategory rows only ever store an English name (see
// prisma/migrations/20260909170000_seed_business_categories) and a
// PublishedListingSnapshot only ever stores that same English name (see
// buildPublishedSnapshot in src/lib/directory.ts, which resolves
// listing.categories to plain category.name strings at approval time,
// discarding the row's id) — so translating a category for display can only
// key off that English string, not an id. Keyed by the exact name seeded in
// that migration; a category name with no entry here (shouldn't happen —
// the list is fixed, not admin-editable, see business-categories.ts) just
// falls back to its English name rather than showing nothing.
const CATEGORY_TRANSLATIONS: Record<string, { zh: string; ms: string }> = {
  "Accounting & Bookkeeping": { zh: "会计与簿记", ms: "Perakaunan & Pembukuan" },
  "Advertising Agency": { zh: "广告代理", ms: "Agensi Pengiklanan" },
  "Agriculture & Farming": { zh: "农业与耕作", ms: "Pertanian & Perladangan" },
  "Air Conditioning & HVAC": { zh: "空调与暖通空调", ms: "Penyaman Udara & HVAC" },
  "Animation & Motion Graphics": { zh: "动画与动态图形", ms: "Animasi & Grafik Gerak" },
  "App Development": { zh: "应用程序开发", ms: "Pembangunan Aplikasi" },
  Architecture: { zh: "建筑设计", ms: "Seni Bina" },
  "Auto Repair & Maintenance": { zh: "汽车维修与保养", ms: "Pembaikan & Penyelenggaraan Kereta" },
  "Automotive Dealership": { zh: "汽车经销商", ms: "Peniaga Automotif" },
  "Aviation Services": { zh: "航空服务", ms: "Perkhidmatan Penerbangan" },
  "Bakery & Confectionery": { zh: "烘焙与糖果", ms: "Bakeri & Gula-gula" },
  "Banking & Financial Services": { zh: "银行与金融服务", ms: "Perbankan & Perkhidmatan Kewangan" },
  "Beauty, Spa & Wellness": { zh: "美容、水疗与健康", ms: "Kecantikan, Spa & Kesejahteraan" },
  "Branding & Graphic Design": { zh: "品牌与平面设计", ms: "Penjenamaan & Reka Bentuk Grafik" },
  "Business Consulting": { zh: "商业咨询", ms: "Perundingan Perniagaan" },
  "Car Rental": { zh: "汽车租赁", ms: "Sewa Kereta" },
  Catering: { zh: "餐饮服务", ms: "Katering" },
  "Childcare & Early Education": { zh: "幼儿托管与早期教育", ms: "Penjagaan Kanak-kanak & Pendidikan Awal" },
  "Cleaning Services": { zh: "清洁服务", ms: "Perkhidmatan Pembersihan" },
  "Cloud & IT Infrastructure": { zh: "云计算与IT基础设施", ms: "Awan & Infrastruktur IT" },
  Construction: { zh: "建筑施工", ms: "Pembinaan" },
  "Content Marketing": { zh: "内容营销", ms: "Pemasaran Kandungan" },
  "Courier & Delivery": { zh: "快递与配送", ms: "Kurier & Penghantaran" },
  Cybersecurity: { zh: "网络安全", ms: "Keselamatan Siber" },
  "Data Analytics & BI": { zh: "数据分析与商业智能", ms: "Analitik Data & BI" },
  "Dental Services": { zh: "牙科服务", ms: "Perkhidmatan Pergigian" },
  "Digital Marketing": { zh: "数字营销", ms: "Pemasaran Digital" },
  "E-commerce": { zh: "电子商务", ms: "E-dagang" },
  "Education & Training": { zh: "教育与培训", ms: "Pendidikan & Latihan" },
  "Electrical Services": { zh: "电气服务", ms: "Perkhidmatan Elektrik" },
  "Electronics & Appliances": { zh: "电子产品与电器", ms: "Elektronik & Perkakas" },
  "Engineering Services": { zh: "工程服务", ms: "Perkhidmatan Kejuruteraan" },
  "Entertainment & Events": { zh: "娱乐与活动", ms: "Hiburan & Acara" },
  "Event Planning": { zh: "活动策划", ms: "Perancangan Acara" },
  "Fashion & Apparel": { zh: "时尚与服装", ms: "Fesyen & Pakaian" },
  "Financial Advisory": { zh: "财务顾问", ms: "Penasihat Kewangan" },
  "Fitness & Gym": { zh: "健身与健身房", ms: "Kecergasan & Gimnasium" },
  "Food & Beverage": { zh: "餐饮食品", ms: "Makanan & Minuman" },
  "Freight & Shipping": { zh: "货运与航运", ms: "Pengangkutan Kargo & Penghantaran" },
  "Furniture & Home Decor": { zh: "家具与家居装饰", ms: "Perabot & Hiasan Rumah" },
  "General Trading": { zh: "一般贸易", ms: "Perdagangan Am" },
  "Government & Public Sector": { zh: "政府与公共部门", ms: "Kerajaan & Sektor Awam" },
  "Hardware & Tools": { zh: "五金与工具", ms: "Perkakasan & Alatan" },
  "Healthcare Services": { zh: "医疗保健服务", ms: "Perkhidmatan Penjagaan Kesihatan" },
  "HR & Recruitment": { zh: "人力资源与招聘", ms: "Sumber Manusia & Pengambilan Pekerja" },
  "Import & Export": { zh: "进出口贸易", ms: "Import & Eksport" },
  "Industrial Equipment": { zh: "工业设备", ms: "Peralatan Industri" },
  Insurance: { zh: "保险", ms: "Insurans" },
  "Interior Design": { zh: "室内设计", ms: "Reka Bentuk Dalaman" },
  "IT Support & Managed Services": { zh: "IT支持与托管服务", ms: "Sokongan IT & Perkhidmatan Terurus" },
  "Landscaping & Gardening": { zh: "园林绿化与园艺", ms: "Landskap & Berkebun" },
  "Legal Services": { zh: "法律服务", ms: "Perkhidmatan Undang-undang" },
  "Logistics & Supply Chain": { zh: "物流与供应链", ms: "Logistik & Rantaian Bekalan" },
  Manufacturing: { zh: "制造业", ms: "Pembuatan" },
  "Marketing Agency": { zh: "营销代理", ms: "Agensi Pemasaran" },
  "Media Production": { zh: "媒体制作", ms: "Produksi Media" },
  "Medical Equipment": { zh: "医疗设备", ms: "Peralatan Perubatan" },
  "Non-Profit & NGO": { zh: "非营利组织与NGO", ms: "Bukan Untung & NGO" },
  "Office Supplies": { zh: "办公用品", ms: "Bekalan Pejabat" },
  Packaging: { zh: "包装", ms: "Pembungkusan" },
  "Pet Services & Veterinary": { zh: "宠物服务与兽医", ms: "Perkhidmatan Haiwan Peliharaan & Veterinar" },
  "Photography & Videography": { zh: "摄影与摄像", ms: "Fotografi & Videografi" },
  "Plumbing Services": { zh: "水管服务", ms: "Perkhidmatan Paip" },
  "Printing & Publishing": { zh: "印刷与出版", ms: "Percetakan & Penerbitan" },
  "Property Management": { zh: "物业管理", ms: "Pengurusan Hartanah" },
  "Public Relations": { zh: "公共关系", ms: "Perhubungan Awam" },
  "Real Estate Agency": { zh: "房地产中介", ms: "Agensi Hartanah" },
  "Renewable & Solar Energy": { zh: "可再生能源与太阳能", ms: "Tenaga Boleh Diperbaharui & Solar" },
  "Restaurant & Cafe": { zh: "餐厅与咖啡厅", ms: "Restoran & Kafe" },
  Retail: { zh: "零售", ms: "Runcit" },
  "Security Services": { zh: "保安服务", ms: "Perkhidmatan Keselamatan" },
  "SEO Services": { zh: "SEO优化服务", ms: "Perkhidmatan SEO" },
  "Social Media Marketing": { zh: "社交媒体营销", ms: "Pemasaran Media Sosial" },
  "Software Development": { zh: "软件开发", ms: "Pembangunan Perisian" },
  "Sports & Recreation": { zh: "体育与休闲", ms: "Sukan & Rekreasi" },
  Telecommunications: { zh: "电信", ms: "Telekomunikasi" },
  Transportation: { zh: "交通运输", ms: "Pengangkutan" },
  "Travel & Tourism": { zh: "旅游与观光", ms: "Perjalanan & Pelancongan" },
  "Tutoring & Coaching": { zh: "补习与辅导", ms: "Tuisyen & Kejurulatihan" },
  "Video Production": { zh: "视频制作", ms: "Produksi Video" },
  Warehousing: { zh: "仓储", ms: "Pergudangan" },
  "Web Design": { zh: "网页设计", ms: "Reka Bentuk Web" },
  "Web Development": { zh: "网页开发", ms: "Pembangunan Web" },
  "Wedding Services": { zh: "婚礼服务", ms: "Perkhidmatan Perkahwinan" },
  "Wholesale & Distribution": { zh: "批发与分销", ms: "Borong & Pengedaran" },
};

export function translateCategoryName(name: string, locale: DirectoryLocale): string {
  if (locale === "en") return name;
  return CATEGORY_TRANSLATIONS[name]?.[locale] ?? name;
}
