import "server-only";

import { mkdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { db } from "@/lib/db";
import { slugify } from "@/lib/slug";
import { DIRECTORY_LOCALES, DIRECTORY_HOME_TITLE_BY_LOCALE, directoryHomePath } from "@/lib/directory-i18n";
import { translateCategoryName, categoryPath } from "@/lib/directory-category-labels";
import { STATIC_SEO_ORIGIN } from "@/lib/static-seo-origin";

// This used to be src/app/llms.txt/route.ts, a Next.js route rendering
// llms.txt (see llmstxt.org) fresh on every request — the GEO counterpart
// to robots.txt/sitemap.xml: a plain-language index an AI system reads
// directly rather than crawling and inferring from HTML. Moved to a plain
// static file (see /public) for the same reason as sitemap.xml (see
// sitemap-generator.ts's own comment on why it's committed to git despite
// being generated content, rather than gitignored).
//
// Only regenerated by deleteBusinessCategory (src/app/actions/
// business-categories.ts) — this file only ever lists the directory home
// page and the category list, never individual businesses, so a listing
// being published/unpublished doesn't change anything it says. Categories
// are otherwise only ever added via migration (see that action's own
// comment), never at runtime, so deletion is the one mutation this needs
// to react to.
const LLMS_TXT_PATH = path.join(process.cwd(), "public", "llms.txt");

function describeLocale(locale: (typeof DIRECTORY_LOCALES)[number]["code"]): string {
  if (locale === "zh") return "Chinese (简体中文)";
  if (locale === "ms") return "Malay (Bahasa Melayu)";
  return "English";
}

export async function buildLlmsTxt(): Promise<string> {
  const categories = await db.businessCategory.findMany({ orderBy: { name: "asc" }, select: { name: true } });

  const lines: string[] = [];
  lines.push(`# ${DIRECTORY_HOME_TITLE_BY_LOCALE.en}`);
  lines.push("");
  lines.push(
    "> A directory of trusted businesses in the Gotka network, searchable by name, service, industry, or category. Each business's own page lists what it offers, its hours, its location, and a direct way to reach it. Published in three languages, each its own real URL rather than a machine translation layered on top.",
  );
  lines.push("");

  lines.push("## Directory home");
  for (const { code } of DIRECTORY_LOCALES) {
    lines.push(
      `- [${describeLocale(code)}](${STATIC_SEO_ORIGIN}${directoryHomePath(code)}): ${DIRECTORY_HOME_TITLE_BY_LOCALE[code]}.`,
    );
  }
  lines.push("");

  if (categories.length > 0) {
    lines.push("## Categories");
    for (const { name } of categories) {
      const slug = slugify(name);
      lines.push(`- [${translateCategoryName(name, "en")}](${STATIC_SEO_ORIGIN}${categoryPath(slug, "en")})`);
    }
    lines.push("");
  }

  lines.push("## Full index");
  lines.push(`- [sitemap.xml](${STATIC_SEO_ORIGIN}/sitemap.xml): Every published business's page, in all three languages.`);

  return lines.join("\n") + "\n";
}

// Same atomic write-then-rename as regenerateSitemapFile — see that
// function's own comment.
export async function regenerateLlmsTxtFile(): Promise<void> {
  const text = await buildLlmsTxt();
  await mkdir(path.dirname(LLMS_TXT_PATH), { recursive: true });
  const tmpPath = `${LLMS_TXT_PATH}.tmp-${process.pid}`;
  await writeFile(tmpPath, text, "utf8");
  await rename(tmpPath, LLMS_TXT_PATH);
}
