import "server-only";

import { mkdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { db } from "@/lib/db";
import { slugify } from "@/lib/slug";
import { countListingsByCategory, countListingsByState, loadPublishedListings } from "@/lib/directory";
import { DIRECTORY_LOCALES, DIRECTORY_HOME_TITLE_BY_LOCALE, directoryHomePath, directoryListingPath } from "@/lib/directory-i18n";
import { translateCategoryName, categoryPath } from "@/lib/directory-category-labels";
import { locationPath } from "@/lib/directory-location-labels";
import { STATIC_SEO_ORIGIN } from "@/lib/static-seo-origin";

// This used to be src/app/llms.txt/route.ts, a Next.js route rendering
// llms.txt (see llmstxt.org) fresh on every request — the GEO counterpart
// to robots.txt/sitemap.xml: a plain-language index an AI system reads
// directly rather than crawling and inferring from HTML. Moved to a plain
// static file (see /public) for the same reason as sitemap.xml (see
// sitemap-generator.ts's own comment on why it's committed to git despite
// being generated content, rather than gitignored).
//
// Regenerated by everything that changes what it says: publishListing/
// unpublishDirectoryListing in src/app/actions/directory.ts (a business
// joins or leaves the Businesses section, and a category may gain or lose
// its only listing) and deleteBusinessCategory in
// src/app/actions/business-categories.ts — plus once on server startup
// (src/instrumentation.ts), same as the sitemap.
const LLMS_TXT_PATH = path.join(process.cwd(), "public", "llms.txt");

function describeLocale(locale: (typeof DIRECTORY_LOCALES)[number]["code"]): string {
  if (locale === "zh") return "Chinese (简体中文)";
  if (locale === "ms") return "Malay (Bahasa Melayu)";
  return "English";
}

// One line of markdown, so a company name or tagline can't inject a
// heading, list item, or line break of its own.
function inline(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

export async function buildLlmsTxt(): Promise<string> {
  const [listings, categories] = await Promise.all([
    loadPublishedListings(),
    db.businessCategory.findMany({ orderBy: { name: "asc" }, select: { name: true } }),
  ]);
  const countByCategory = countListingsByCategory(listings);

  const lines: string[] = [];
  lines.push(`# ${DIRECTORY_HOME_TITLE_BY_LOCALE.en}`);
  lines.push("");
  lines.push(
    "> A directory of trusted businesses in the Gotka partner network, published by Gotka Technologies and searchable by name, service, industry, or category. Every listing is reviewed before it is published. Each business's own page lists what it offers, its hours, its location, an FAQ, and a contact form that reaches the business directly. Published in three languages, each its own real URL rather than a machine translation layered on top.",
  );
  lines.push("");

  lines.push("## Directory home");
  for (const { code } of DIRECTORY_LOCALES) {
    lines.push(
      `- [${describeLocale(code)}](${STATIC_SEO_ORIGIN}${directoryHomePath(code)}): ${DIRECTORY_HOME_TITLE_BY_LOCALE[code]}.`,
    );
  }
  lines.push("");

  // Only categories with a published business in them — the empty ones are
  // pages of nothing but "No businesses found" (noindex, and absent from the
  // sitemap for the same reason; see buildCategoryMetadata).
  const populatedCategories = categories.filter(({ name }) => (countByCategory.get(name) ?? 0) > 0);
  if (populatedCategories.length > 0) {
    lines.push("## Categories");
    for (const { name } of populatedCategories) {
      const slug = slugify(name);
      const count = countByCategory.get(name) ?? 0;
      lines.push(
        `- [${translateCategoryName(name, "en")}](${STATIC_SEO_ORIGIN}${categoryPath(slug, "en")}): ${count} ${count === 1 ? "business" : "businesses"}`,
      );
    }
    lines.push("");
  }

  // Every state at least one published listing carries — unlike
  // categories, there's no "empty" one to filter out (see
  // countListingsByState).
  const countByState = countListingsByState(listings);
  if (countByState.size > 0) {
    lines.push("## Locations");
    for (const [state, count] of countByState) {
      const slug = slugify(state);
      lines.push(`- [${inline(state)}](${STATIC_SEO_ORIGIN}${locationPath(slug, "en")}): ${count} ${count === 1 ? "business" : "businesses"}`);
    }
    lines.push("");
  }

  // The businesses themselves, one line each — the thing an AI system is
  // most likely to be asked about, and the one part of this index that used
  // to be findable only by crawling the sitemap's URLs one by one.
  if (listings.length > 0) {
    lines.push("## Businesses");
    for (const { slug, listing } of listings) {
      const summary = listing.seoDescription?.trim() || listing.tagline?.trim() || "";
      const where = [listing.state, listing.country].filter((part): part is string => Boolean(part?.trim())).join(", ");
      lines.push(
        `- [${inline(listing.companyName)}](${STATIC_SEO_ORIGIN}${directoryListingPath("en", slug)})` +
          (summary ? `: ${inline(summary)}` : "") +
          (where ? ` (${inline(where)})` : ""),
      );
    }
    lines.push("");
  }

  lines.push("## Full index");
  lines.push(`- [sitemap.xml](${STATIC_SEO_ORIGIN}/sitemap.xml): Every published business's page, in all three languages.`);

  return lines.join("\n") + "\n";
}

// Same atomic write-then-rename as regenerateSitemapFile — see that
// function's own comment.
export async function regenerateLlmsTxtFile(): Promise<void> {
  const text = await buildLlmsTxt();
  await mkdir(path.dirname(LLMS_TXT_PATH), { recursive: true });
  const tmpPath = `${LLMS_TXT_PATH}.tmp-${process.pid}`;
  await writeFile(tmpPath, text, "utf8");
  await rename(tmpPath, LLMS_TXT_PATH);
}
