import "server-only";

import { mkdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { db } from "@/lib/db";
import { slugify } from "@/lib/directory";
import { categoryPath } from "@/lib/directory-category-labels";
import { DIRECTORY_LOCALES, directoryHomePath, directoryListingPath, type DirectoryLocale } from "@/lib/directory-i18n";
import { STATIC_SEO_ORIGIN } from "@/lib/static-seo-origin";

// This used to be src/app/sitemap.ts, a Next.js route rendering
// sitemap.xml fresh on every request. Moved to a plain static file (see
// /public) generated ahead of time instead — regenerated by every action
// that changes what belongs in it (publishListing/unpublishDirectoryListing
// in src/app/actions/directory.ts, deleteBusinessCategory in
// src/app/actions/business-categories.ts) rather than rendered per
// request. instrumentation.ts also regenerates it once on server startup,
// so an accidentally-stale file self-heals without needing to wait for the
// next publish/unpublish.
//
// /public/sitemap.xml IS committed to git (a minimal placeholder — see
// that file) despite being generated content, unlike this repo's other
// runtime-written /public files (e.g. /public/uploads/, gitignored).
// That's not a style choice: Next.js decides which /public paths exist at
// `next build` time, baked into that build's own output — a file that
// didn't exist yet at build time can never be served afterward, no matter
// what writes it at runtime, until the *next* build. A gitignored
// sitemap.xml would 404 forever on this app's very first deploy after this
// feature shipped. Once the path exists in at least one build, though,
// every later request reads the file's current content fresh off disk —
// which is what makes overwriting it at runtime (regenerateSitemapFile,
// below) work at all after that.
const SITEMAP_PATH = path.join(process.cwd(), "public", "sitemap.xml");

function languageAlternates(pathFor: (locale: DirectoryLocale) => string): string {
  return DIRECTORY_LOCALES.map(
    ({ code }) => `<xhtml:link rel="alternate" hreflang="${code}" href="${STATIC_SEO_ORIGIN}${pathFor(code)}" />`,
  ).join("");
}

function urlEntry(
  url: string,
  options: { alternates?: string; lastModified?: Date; changeFrequency: string; priority: number },
): string {
  const parts = [`<loc>${url}</loc>`];
  if (options.alternates) parts.push(options.alternates);
  if (options.lastModified) parts.push(`<lastmod>${options.lastModified.toISOString()}</lastmod>`);
  parts.push(`<changefreq>${options.changeFrequency}</changefreq>`);
  parts.push(`<priority>${options.priority}</priority>`);
  return `<url>${parts.join("")}</url>`;
}

// Every language of every page is its own real, indexable URL (see
// directoryHomePath/directoryListingPath/categoryPath) — so each gets its
// own <url> entry, carrying hreflang alternates back to the other two
// (itself included, which is what a correct hreflang set requires) rather
// than one "canonical" URL with the others only referenced as alternates.
//
// /business-portal is listed too — a partner searching for their own
// portal by name is a real use case, and it's login-gated regardless (see
// /public/robots.txt), so nothing behind it is actually reachable by a
// crawler either way. /system (the internal staff CRM) is deliberately
// NOT listed — nobody outside the company is ever going to search for it
// by name, so there's no upside to naming it in a document search engines
// actually read.
export async function buildSitemapXml(): Promise<string> {
  const [listings, categories] = await Promise.all([
    db.partnerListing.findMany({
      where: { status: "PUBLISHED" },
      select: { slug: true, updatedAt: true },
      orderBy: { updatedAt: "desc" },
    }),
    db.businessCategory.findMany({ orderBy: { name: "asc" }, select: { name: true } }),
  ]);

  const entries: string[] = [];

  entries.push(urlEntry(`${STATIC_SEO_ORIGIN}/business-portal`, { changeFrequency: "monthly", priority: 0.3 }));

  for (const { code } of DIRECTORY_LOCALES) {
    entries.push(
      urlEntry(`${STATIC_SEO_ORIGIN}${directoryHomePath(code)}`, {
        alternates: languageAlternates(directoryHomePath),
        changeFrequency: "daily",
        priority: 0.8,
      }),
    );
  }

  for (const { name } of categories) {
    const categorySlug = slugify(name);
    for (const { code } of DIRECTORY_LOCALES) {
      entries.push(
        urlEntry(`${STATIC_SEO_ORIGIN}${categoryPath(categorySlug, code)}`, {
          alternates: languageAlternates((locale) => categoryPath(categorySlug, locale)),
          changeFrequency: "daily",
          priority: 0.7,
        }),
      );
    }
  }

  for (const { slug, updatedAt } of listings) {
    for (const { code } of DIRECTORY_LOCALES) {
      entries.push(
        urlEntry(`${STATIC_SEO_ORIGIN}${directoryListingPath(code, slug)}`, {
          alternates: languageAlternates((locale) => directoryListingPath(locale, slug)),
          lastModified: updatedAt,
          changeFrequency: "weekly",
          priority: 0.6,
        }),
      );
    }
  }

  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n` +
    entries.join("\n") +
    `\n</urlset>\n`
  );
}

// Written to a temp file and renamed into place rather than written
// directly — rename is atomic on the same filesystem, so a request landing
// mid-regeneration always sees either the old complete file or the new
// complete one, never a half-written one (this file is served straight off
// disk by the web server, not proxied through anything that would buffer a
// partial read).
export async function regenerateSitemapFile(): Promise<void> {
  const xml = await buildSitemapXml();
  await mkdir(path.dirname(SITEMAP_PATH), { recursive: true });
  const tmpPath = `${SITEMAP_PATH}.tmp-${process.pid}`;
  await writeFile(tmpPath, xml, "utf8");
  await rename(tmpPath, SITEMAP_PATH);
}
