import "server-only";

import { mkdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { db } from "@/lib/db";
import { countListingsByCategory, loadPublishedListings, slugify } from "@/lib/directory";
import { categoryPath } from "@/lib/directory-category-labels";
import {
  DEFAULT_DIRECTORY_LOCALE,
  DIRECTORY_LOCALES,
  directoryHomePath,
  directoryListingPath,
  type DirectoryLocale,
} from "@/lib/directory-i18n";
import { STATIC_SEO_ORIGIN } from "@/lib/static-seo-origin";

// This used to be src/app/sitemap.ts, a Next.js route rendering
// sitemap.xml fresh on every request. Moved to a plain static file (see
// /public) generated ahead of time instead — regenerated by every action
// that changes what belongs in it (publishListing/unpublishDirectoryListing
// in src/app/actions/directory.ts, deleteBusinessCategory in
// src/app/actions/business-categories.ts) rather than rendered per
// request. instrumentation.ts also regenerates it once on server startup,
// so an accidentally-stale file self-heals without needing to wait for the
// next publish/unpublish.
//
// /public/sitemap.xml IS committed to git (a minimal placeholder — see
// that file) despite being generated content, unlike this repo's other
// runtime-written /public files (e.g. /public/uploads/, gitignored).
// That's not a style choice: Next.js decides which /public paths exist at
// `next build` time, baked into that build's own output — a file that
// didn't exist yet at build time can never be served afterward, no matter
// what writes it at runtime, until the *next* build. A gitignored
// sitemap.xml would 404 forever on this app's very first deploy after this
// feature shipped. Once the path exists in at least one build, though,
// every later request reads the file's current content fresh off disk —
// which is what makes overwriting it at runtime (regenerateSitemapFile,
// below) work at all after that.
const SITEMAP_PATH = path.join(process.cwd(), "public", "sitemap.xml");

// The same set each page's own <head> declares (see buildLanguageAlternates
// in directory-seo.ts): all three languages plus x-default → English.
function languageAlternates(pathFor: (locale: DirectoryLocale) => string): string {
  const alternates: [string, string][] = DIRECTORY_LOCALES.map(({ code }) => [code, pathFor(code)]);
  alternates.push(["x-default", pathFor(DEFAULT_DIRECTORY_LOCALE)]);
  return alternates
    .map(([code, path]) => `<xhtml:link rel="alternate" hreflang="${code}" href="${STATIC_SEO_ORIGIN}${path}" />`)
    .join("");
}

function urlEntry(
  url: string,
  options: { alternates?: string; lastModified?: Date; changeFrequency: string; priority: number },
): string {
  const parts = [`<loc>${url}</loc>`];
  if (options.alternates) parts.push(options.alternates);
  if (options.lastModified) parts.push(`<lastmod>${options.lastModified.toISOString()}</lastmod>`);
  parts.push(`<changefreq>${options.changeFrequency}</changefreq>`);
  parts.push(`<priority>${options.priority}</priority>`);
  return `<url>${parts.join("")}</url>`;
}

// Every language of every page is its own real, indexable URL (see
// directoryHomePath/directoryListingPath/categoryPath) — so each gets its
// own <url> entry, carrying hreflang alternates back to the other two
// (itself included, which is what a correct hreflang set requires) rather
// than one "canonical" URL with the others only referenced as alternates.
//
// Only the public directory is listed. The partner portal and the staff CRM
// both sit behind a login (and the portal declares itself noindex), so
// naming them here would only send crawlers to a sign-in form.
export async function buildSitemapXml(): Promise<string> {
  const [listings, categories] = await Promise.all([
    loadPublishedListings(),
    db.businessCategory.findMany({ orderBy: { name: "asc" }, select: { name: true } }),
  ]);
  const countByCategory = countListingsByCategory(listings);

  const entries: string[] = [];

  for (const { code } of DIRECTORY_LOCALES) {
    entries.push(
      urlEntry(`${STATIC_SEO_ORIGIN}${directoryHomePath(code)}`, {
        alternates: languageAlternates(directoryHomePath),
        changeFrequency: "daily",
        priority: 0.8,
      }),
    );
  }

  for (const { name } of categories) {
    // A category nobody has published into yet is noindex (see
    // buildCategoryMetadata) — listing it here would only send crawlers to
    // a page that then asks not to be indexed. It joins the moment a
    // published listing carries it, since every publish regenerates this.
    if (!(countByCategory.get(name) ?? 0)) continue;
    const categorySlug = slugify(name);
    for (const { code } of DIRECTORY_LOCALES) {
      entries.push(
        urlEntry(`${STATIC_SEO_ORIGIN}${categoryPath(categorySlug, code)}`, {
          alternates: languageAlternates((locale) => categoryPath(categorySlug, locale)),
          changeFrequency: "daily",
          priority: 0.7,
        }),
      );
    }
  }

  // The public page only changes when a snapshot is approved, so the
  // publish time is the honest lastmod; updatedAt moves on every draft save
  // the public never sees, and a lastmod that lies gets ignored.
  for (const { slug, publishedAt, updatedAt } of listings) {
    for (const { code } of DIRECTORY_LOCALES) {
      entries.push(
        urlEntry(`${STATIC_SEO_ORIGIN}${directoryListingPath(code, slug)}`, {
          alternates: languageAlternates((locale) => directoryListingPath(locale, slug)),
          lastModified: publishedAt ?? updatedAt,
          changeFrequency: "weekly",
          priority: 0.6,
        }),
      );
    }
  }

  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n` +
    entries.join("\n") +
    `\n</urlset>\n`
  );
}

// Written to a temp file and renamed into place rather than written
// directly — rename is atomic on the same filesystem, so a request landing
// mid-regeneration always sees either the old complete file or the new
// complete one, never a half-written one (this file is served straight off
// disk by the web server, not proxied through anything that would buffer a
// partial read).
export async function regenerateSitemapFile(): Promise<void> {
  const xml = await buildSitemapXml();
  await mkdir(path.dirname(SITEMAP_PATH), { recursive: true });
  const tmpPath = `${SITEMAP_PATH}.tmp-${process.pid}`;
  await writeFile(tmpPath, xml, "utf8");
  await rename(tmpPath, SITEMAP_PATH);
}
