-- Settings → Directory no longer lets an admin type in a new category
-- (see src/app/actions/business-categories.ts) — this backfills a full,
-- curated starter vocabulary in its place so the partner listing picker
-- isn't left empty. Fixed, readable ids rather than generated cuids —
-- there's no server-side id generator available inside plain SQL, and a
-- stable slug is more debuggable for what are effectively system rows.
-- INSERT IGNORE so this is safe to apply even where an admin already
-- created a same-named category by hand before this migration landed.
INSERT IGNORE INTO `BusinessCategory` (`id`, `name`) VALUES
    ('category-accounting-bookkeeping', 'Accounting & Bookkeeping'),
    ('category-advertising-agency', 'Advertising Agency'),
    ('category-agriculture-farming', 'Agriculture & Farming'),
    ('category-air-conditioning-hvac', 'Air Conditioning & HVAC'),
    ('category-animation-motion-graphics', 'Animation & Motion Graphics'),
    ('category-app-development', 'App Development'),
    ('category-architecture', 'Architecture'),
    ('category-auto-repair-maintenance', 'Auto Repair & Maintenance'),
    ('category-automotive-dealership', 'Automotive Dealership'),
    ('category-aviation-services', 'Aviation Services'),
    ('category-bakery-confectionery', 'Bakery & Confectionery'),
    ('category-banking-financial-services', 'Banking & Financial Services'),
    ('category-beauty-spa-wellness', 'Beauty, Spa & Wellness'),
    ('category-branding-graphic-design', 'Branding & Graphic Design'),
    ('category-business-consulting', 'Business Consulting'),
    ('category-car-rental', 'Car Rental'),
    ('category-catering', 'Catering'),
    ('category-childcare-early-education', 'Childcare & Early Education'),
    ('category-cleaning-services', 'Cleaning Services'),
    ('category-cloud-it-infrastructure', 'Cloud & IT Infrastructure'),
    ('category-construction', 'Construction'),
    ('category-content-marketing', 'Content Marketing'),
    ('category-courier-delivery', 'Courier & Delivery'),
    ('category-cybersecurity', 'Cybersecurity'),
    ('category-data-analytics-bi', 'Data Analytics & BI'),
    ('category-dental-services', 'Dental Services'),
    ('category-digital-marketing', 'Digital Marketing'),
    ('category-ecommerce', 'E-commerce'),
    ('category-education-training', 'Education & Training'),
    ('category-electrical-services', 'Electrical Services'),
    ('category-electronics-appliances', 'Electronics & Appliances'),
    ('category-engineering-services', 'Engineering Services'),
    ('category-entertainment-events', 'Entertainment & Events'),
    ('category-event-planning', 'Event Planning'),
    ('category-fashion-apparel', 'Fashion & Apparel'),
    ('category-financial-advisory', 'Financial Advisory'),
    ('category-fitness-gym', 'Fitness & Gym'),
    ('category-food-beverage', 'Food & Beverage'),
    ('category-freight-shipping', 'Freight & Shipping'),
    ('category-furniture-home-decor', 'Furniture & Home Decor'),
    ('category-general-trading', 'General Trading'),
    ('category-government-public-sector', 'Government & Public Sector'),
    ('category-hardware-tools', 'Hardware & Tools'),
    ('category-healthcare-services', 'Healthcare Services'),
    ('category-hr-recruitment', 'HR & Recruitment'),
    ('category-import-export', 'Import & Export'),
    ('category-industrial-equipment', 'Industrial Equipment'),
    ('category-insurance', 'Insurance'),
    ('category-interior-design', 'Interior Design'),
    ('category-it-support-managed-services', 'IT Support & Managed Services'),
    ('category-landscaping-gardening', 'Landscaping & Gardening'),
    ('category-legal-services', 'Legal Services'),
    ('category-logistics-supply-chain', 'Logistics & Supply Chain'),
    ('category-manufacturing', 'Manufacturing'),
    ('category-marketing-agency', 'Marketing Agency'),
    ('category-media-production', 'Media Production'),
    ('category-medical-equipment', 'Medical Equipment'),
    ('category-non-profit-ngo', 'Non-Profit & NGO'),
    ('category-office-supplies', 'Office Supplies'),
    ('category-packaging', 'Packaging'),
    ('category-pet-services-veterinary', 'Pet Services & Veterinary'),
    ('category-photography-videography', 'Photography & Videography'),
    ('category-plumbing-services', 'Plumbing Services'),
    ('category-printing-publishing', 'Printing & Publishing'),
    ('category-property-management', 'Property Management'),
    ('category-public-relations', 'Public Relations'),
    ('category-real-estate-agency', 'Real Estate Agency'),
    ('category-renewable-solar-energy', 'Renewable & Solar Energy'),
    ('category-restaurant-cafe', 'Restaurant & Cafe'),
    ('category-retail', 'Retail'),
    ('category-security-services', 'Security Services'),
    ('category-seo-services', 'SEO Services'),
    ('category-social-media-marketing', 'Social Media Marketing'),
    ('category-software-development', 'Software Development'),
    ('category-sports-recreation', 'Sports & Recreation'),
    ('category-telecommunications', 'Telecommunications'),
    ('category-transportation', 'Transportation'),
    ('category-travel-tourism', 'Travel & Tourism'),
    ('category-tutoring-coaching', 'Tutoring & Coaching'),
    ('category-video-production', 'Video Production'),
    ('category-warehousing', 'Warehousing'),
    ('category-web-design', 'Web Design'),
    ('category-web-development', 'Web Development'),
    ('category-wedding-services', 'Wedding Services'),
    ('category-wholesale-distribution', 'Wholesale & Distribution');
