-- Any existing free-text value that doesn't exactly match one of the new
-- categories becomes unclassified (NULL) rather than being force-fit into
-- the wrong bucket or blocking the type change below.
UPDATE `Company` SET `industry` = NULL WHERE `industry` NOT IN (
  'TECHNOLOGY', 'RETAIL_ECOMMERCE', 'HEALTHCARE', 'FINANCE_BANKING', 'MANUFACTURING',
  'CONSTRUCTION_REAL_ESTATE', 'EDUCATION', 'HOSPITALITY_TOURISM', 'PROFESSIONAL_SERVICES',
  'MEDIA_ENTERTAINMENT', 'TRANSPORTATION_LOGISTICS', 'AGRICULTURE', 'ENERGY_UTILITIES',
  'GOVERNMENT_NONPROFIT', 'TELECOMMUNICATIONS', 'AUTOMOTIVE', 'FOOD_BEVERAGE', 'LEGAL',
  'MARKETING_ADVERTISING', 'OTHER'
);

-- AlterTable
ALTER TABLE `Company` MODIFY COLUMN `industry` ENUM(
  'TECHNOLOGY', 'RETAIL_ECOMMERCE', 'HEALTHCARE', 'FINANCE_BANKING', 'MANUFACTURING',
  'CONSTRUCTION_REAL_ESTATE', 'EDUCATION', 'HOSPITALITY_TOURISM', 'PROFESSIONAL_SERVICES',
  'MEDIA_ENTERTAINMENT', 'TRANSPORTATION_LOGISTICS', 'AGRICULTURE', 'ENERGY_UTILITIES',
  'GOVERNMENT_NONPROFIT', 'TELECOMMUNICATIONS', 'AUTOMOTIVE', 'FOOD_BEVERAGE', 'LEGAL',
  'MARKETING_ADVERTISING', 'OTHER'
) NULL;
