-- Rounds out the starter vocabulary from
-- prisma/migrations/20260909170000_seed_business_categories with the
-- healthcare, legal/compliance, finance, construction trades,
-- manufacturing, retail, F&B, hospitality, automotive, agriculture,
-- energy, education, technology and personal/professional-service
-- categories that vocabulary didn't cover — the category picker still
-- isn't admin-editable (see src/app/actions/business-categories.ts), so
-- a gap here has no other way to close. Same fixed-id, INSERT IGNORE
-- pattern as that migration, for the same reasons.
INSERT IGNORE INTO `BusinessCategory` (`id`, `name`) VALUES
    ('category-medical-clinic-gp', 'Medical Clinic & GP'),
    ('category-pharmacy', 'Pharmacy'),
    ('category-physiotherapy-rehabilitation', 'Physiotherapy & Rehabilitation'),
    ('category-traditional-complementary-medicine', 'Traditional & Complementary Medicine'),
    ('category-optical-eyewear', 'Optical & Eyewear'),
    ('category-nursing-home-care', 'Nursing & Home Care'),
    ('category-aesthetic-cosmetic-clinic', 'Aesthetic & Cosmetic Clinic'),
    ('category-mental-health-counselling', 'Mental Health & Counselling'),
    ('category-nutrition-dietetics', 'Nutrition & Dietetics'),
    ('category-hair-salon-barbershop', 'Hair Salon & Barbershop'),
    ('category-nail-salon', 'Nail Salon'),
    ('category-tattoo-piercing-studio', 'Tattoo & Piercing Studio'),
    ('category-company-secretarial-services', 'Company Secretarial Services'),
    ('category-tax-agent-advisory', 'Tax Agent & Advisory'),
    ('category-trademark-ip-services', 'Trademark & IP Services'),
    ('category-notary-commissioner-oaths', 'Notary & Commissioner for Oaths'),
    ('category-insurance-broker-agency', 'Insurance Broker & Agency'),
    ('category-money-changer-remittance', 'Money Changer & Remittance'),
    ('category-islamic-finance-banking', 'Islamic Finance & Banking'),
    ('category-payment-gateway-fintech', 'Payment Gateway & Fintech'),
    ('category-investment-wealth-management', 'Investment & Wealth Management'),
    ('category-stockbroking-unit-trust', 'Stockbroking & Unit Trust'),
    ('category-debt-collection-recovery', 'Debt Collection & Recovery'),
    ('category-pawnbroking', 'Pawnbroking'),
    ('category-renovation-remodeling', 'Renovation & Remodeling'),
    ('category-roofing-services', 'Roofing Services'),
    ('category-waterproofing-services', 'Waterproofing Services'),
    ('category-glass-aluminum-works', 'Glass & Aluminum Works'),
    ('category-signage-fabrication', 'Signage & Fabrication'),
    ('category-scaffolding-formwork', 'Scaffolding & Formwork'),
    ('category-welding-metalwork', 'Welding & Metalwork'),
    ('category-flooring-tiling', 'Flooring & Tiling'),
    ('category-painting-services', 'Painting Services'),
    ('category-plastics-rubber-manufacturing', 'Plastics & Rubber Manufacturing'),
    ('category-metal-fabrication', 'Metal Fabrication'),
    ('category-food-beverage-manufacturing', 'Food & Beverage Manufacturing'),
    ('category-textile-garment-manufacturing', 'Textile & Garment Manufacturing'),
    ('category-furniture-manufacturing', 'Furniture Manufacturing'),
    ('category-supermarket-grocery', 'Supermarket & Grocery'),
    ('category-convenience-store', 'Convenience Store'),
    ('category-jewelry-watches', 'Jewelry & Watches'),
    ('category-bookstore-stationery', 'Bookstore & Stationery'),
    ('category-food-truck-hawker', 'Food Truck & Hawker'),
    ('category-bar-nightlife', 'Bar & Nightlife'),
    ('category-coffee-roaster-cafe-supply', 'Coffee Roaster & Café Supply'),
    ('category-hotel-resort', 'Hotel & Resort'),
    ('category-homestay-vacation-rental', 'Homestay & Vacation Rental'),
    ('category-car-wash-detailing', 'Car Wash & Detailing'),
    ('category-tyre-shop-wheel-services', 'Tyre Shop & Wheel Services'),
    ('category-motorcycle-dealership-repair', 'Motorcycle Dealership & Repair'),
    ('category-livestock-poultry-farming', 'Livestock & Poultry Farming'),
    ('category-fisheries-aquaculture', 'Fisheries & Aquaculture'),
    ('category-agrotechnology', 'Agrotechnology'),
    ('category-oil-gas-services', 'Oil & Gas Services'),
    ('category-waste-management-recycling', 'Waste Management & Recycling'),
    ('category-environmental-esg-consulting', 'Environmental & ESG Consulting'),
    ('category-kindergarten-preschool', 'Kindergarten & Preschool'),
    ('category-international-private-school', 'International & Private School'),
    ('category-driving-school', 'Driving School'),
    ('category-language-school', 'Language School'),
    ('category-vocational-skills-training', 'Vocational & Skills Training'),
    ('category-martial-arts-combat-sports', 'Martial Arts & Combat Sports'),
    ('category-game-development', 'Game Development'),
    ('category-blockchain-web3', 'Blockchain & Web3'),
    ('category-ai-machine-learning-consulting', 'AI & Machine Learning Consulting'),
    ('category-iot-embedded-systems', 'IoT & Embedded Systems'),
    ('category-pest-control-services', 'Pest Control Services'),
    ('category-domestic-helper-maid-agency', 'Domestic Helper & Maid Agency'),
    ('category-funeral-bereavement-services', 'Funeral & Bereavement Services'),
    ('category-locksmith-services', 'Locksmith Services'),
    ('category-moving-relocation-services', 'Moving & Relocation Services'),
    ('category-translation-interpretation', 'Translation & Interpretation'),
    ('category-market-research', 'Market Research'),
    ('category-business-process-outsourcing', 'Business Process Outsourcing (BPO)'),
    ('category-talent-influencer-agency', 'Talent & Influencer Agency');
