"use server";

import { randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { db } from "@/lib/db";
import { hashPassword, verifyPassword } from "@/lib/auth/password";
import { verifySession } from "@/lib/auth/dal";

const createUserSchema = z.object({
  name: z.string().trim().min(1, "Name is required"),
  email: z.string().trim().toLowerCase().email("Enter a valid email address"),
  title: z.string().trim().optional(),
  password: z.string().trim().optional(),
});

export type CreateUserState =
  | { error: string }
  | { success: true; email: string; password: string; autoGenerated: boolean }
  | undefined;

export async function createUser(
  _prevState: CreateUserState,
  formData: FormData,
): Promise<CreateUserState> {
  await verifySession();

  const parsed = createUserSchema.safeParse({
    name: formData.get("name"),
    email: formData.get("email"),
    title: formData.get("title"),
    password: formData.get("password"),
  });
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Invalid input" };
  }

  const existing = await db.user.findUnique({ where: { email: parsed.data.email } });
  if (existing) {
    return { error: "A user with that email already exists." };
  }

  const chosenPassword = parsed.data.password?.trim();
  if (chosenPassword && chosenPassword.length < 8) {
    return { error: "Password must be at least 8 characters." };
  }
  const autoGenerated = !chosenPassword;
  const password = chosenPassword || randomBytes(9).toString("base64url");

  await db.user.create({
    data: {
      name: parsed.data.name,
      email: parsed.data.email,
      title: parsed.data.title || null,
      passwordHash: await hashPassword(password),
    },
  });

  revalidatePath("/settings");
  return { success: true, email: parsed.data.email, password, autoGenerated };
}

export async function deleteUser(userId: string) {
  const session = await verifySession();
  if (session.userId === userId) {
    throw new Error("You can't delete your own account while logged in.");
  }
  const count = await db.user.count();
  if (count <= 1) {
    throw new Error("Can't delete the last remaining user.");
  }
  await db.user.delete({ where: { id: userId } });
  revalidatePath("/settings");
}

export type ResetPasswordState = { error: string } | { success: true; password: string } | undefined;

export async function resetUserPassword(
  userId: string,
  prevState: ResetPasswordState,
  formData: FormData,
): Promise<ResetPasswordState> {
  void prevState;
  void formData;
  const session = await verifySession();
  if (session.userId === userId) {
    return { error: 'Use "Change your password" below to update your own password.' };
  }

  const password = randomBytes(9).toString("base64url");
  await db.user.update({
    where: { id: userId },
    data: { passwordHash: await hashPassword(password) },
  });

  revalidatePath("/settings");
  return { success: true, password };
}

const changePasswordSchema = z.object({
  currentPassword: z.string().min(1, "Current password is required"),
  newPassword: z.string().min(8, "New password must be at least 8 characters"),
});

export type ChangePasswordState = { error: string } | { success: true } | undefined;

export async function changePassword(
  _prevState: ChangePasswordState,
  formData: FormData,
): Promise<ChangePasswordState> {
  const session = await verifySession();

  const parsed = changePasswordSchema.safeParse({
    currentPassword: formData.get("currentPassword"),
    newPassword: formData.get("newPassword"),
  });
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Invalid input" };
  }

  const user = await db.user.findUniqueOrThrow({ where: { id: session.userId } });
  const valid = await verifyPassword(parsed.data.currentPassword, user.passwordHash);
  if (!valid) {
    return { error: "Current password is incorrect." };
  }

  await db.user.update({
    where: { id: user.id },
    data: { passwordHash: await hashPassword(parsed.data.newPassword) },
  });

  return { success: true };
}
