"use server";

import { randomBytes } from "node:crypto";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { db } from "@/lib/db";
import { hashPassword, verifyPassword } from "@/lib/auth/password";
import { verifySession, requireAdminAction } from "@/lib/auth/dal";
import { isValidPhoneFormat, normalizePhone, PHONE_FORMAT_HINT } from "@/lib/phone";
import type { Role } from "@/generated/prisma/client";

const createUserSchema = z.object({
  name: z.string().trim().min(1, "Name is required"),
  email: z.string().trim().toLowerCase().email("Enter a valid email address"),
  title: z.string().trim().optional(),
  password: z.string().trim().optional(),
  role: z.enum(["ADMIN", "DEVELOPER"]),
});

export type CreateUserState =
  | { error: string }
  | { success: true; email: string; password: string; autoGenerated: boolean }
  | undefined;

export async function createUser(
  _prevState: CreateUserState,
  formData: FormData,
): Promise<CreateUserState> {
  await requireAdminAction();

  const parsed = createUserSchema.safeParse({
    name: formData.get("name"),
    email: formData.get("email"),
    title: formData.get("title"),
    password: formData.get("password"),
    role: formData.get("role"),
  });
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Invalid input" };
  }

  const existing = await db.user.findUnique({ where: { email: parsed.data.email } });
  if (existing) {
    return { error: "A user with that email already exists." };
  }

  const chosenPassword = parsed.data.password?.trim();
  if (chosenPassword && chosenPassword.length < 8) {
    return { error: "Password must be at least 8 characters." };
  }
  const autoGenerated = !chosenPassword;
  const password = chosenPassword || randomBytes(9).toString("base64url");

  await db.user.create({
    data: {
      name: parsed.data.name,
      email: parsed.data.email,
      title: parsed.data.title || null,
      role: parsed.data.role as Role,
      passwordHash: await hashPassword(password),
    },
  });

  revalidatePath("/settings");
  return { success: true, email: parsed.data.email, password, autoGenerated };
}

const hourlyRateSchema = z.object({
  rate: z
    .string()
    .trim()
    .optional()
    .transform((value) => (value ? value : null))
    .refine((value) => value === null || (!Number.isNaN(Number(value)) && Number(value) >= 0), {
      message: "Enter a valid, non-negative rate",
    }),
});

export async function updateUserRate(userId: string, formData: FormData) {
  await requireAdminAction();

  const parsed = hourlyRateSchema.safeParse({ rate: formData.get("rate") });
  if (!parsed.success) {
    throw new Error(parsed.error.issues[0]?.message ?? "Invalid rate");
  }

  await db.user.update({
    where: { id: userId },
    data: { hourlyRate: parsed.data.rate },
  });

  revalidatePath("/settings");
}

export async function updateUserRole(userId: string, role: Role) {
  const session = await requireAdminAction();
  if (session.id === userId) {
    throw new Error("You can't change your own role.");
  }
  await db.user.update({ where: { id: userId }, data: { role } });
  revalidatePath("/settings");
}

export async function deleteUser(userId: string) {
  await requireAdminAction();
  const session = await verifySession();
  if (session.userId === userId) {
    throw new Error("You can't delete your own account while logged in.");
  }
  const count = await db.user.count();
  if (count <= 1) {
    throw new Error("Can't delete the last remaining user.");
  }
  await db.user.delete({ where: { id: userId } });
  revalidatePath("/settings");
}

export type ResetPasswordState = { error: string } | { success: true; password: string } | undefined;

export async function resetUserPassword(
  userId: string,
  prevState: ResetPasswordState,
  formData: FormData,
): Promise<ResetPasswordState> {
  void prevState;
  void formData;
  await requireAdminAction();
  const session = await verifySession();
  if (session.userId === userId) {
    return { error: 'Use "Change your password" below to update your own password.' };
  }

  const password = randomBytes(9).toString("base64url");
  await db.user.update({
    where: { id: userId },
    data: { passwordHash: await hashPassword(password) },
  });

  revalidatePath("/settings");
  return { success: true, password };
}

const changePasswordSchema = z.object({
  currentPassword: z.string().min(1, "Current password is required"),
  newPassword: z.string().min(8, "New password must be at least 8 characters"),
});

export type ChangePasswordState = { error: string } | { success: true } | undefined;

export async function changePassword(
  _prevState: ChangePasswordState,
  formData: FormData,
): Promise<ChangePasswordState> {
  const session = await verifySession();

  const parsed = changePasswordSchema.safeParse({
    currentPassword: formData.get("currentPassword"),
    newPassword: formData.get("newPassword"),
  });
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Invalid input" };
  }

  const user = await db.user.findUniqueOrThrow({ where: { id: session.userId } });
  const valid = await verifyPassword(parsed.data.currentPassword, user.passwordHash);
  if (!valid) {
    return { error: "Current password is incorrect." };
  }

  await db.user.update({
    where: { id: user.id },
    data: { passwordHash: await hashPassword(parsed.data.newPassword) },
  });

  return { success: true };
}

const myPhoneSchema = z.object({
  phone: z
    .string()
    .trim()
    .optional()
    .refine((value) => !value || isValidPhoneFormat(value), { message: PHONE_FORMAT_HINT }),
});

export type MyPhoneState = { error: string } | { success: true } | undefined;

// Self-service, like changePassword above — sets only the caller's own
// number, for their own WhatsApp task-reminder opt-in (see
// scripts/send-task-digests-whatsapp.ts). Clearing the field (blank) opts
// back out.
export async function updateMyPhone(
  _prevState: MyPhoneState,
  formData: FormData,
): Promise<MyPhoneState> {
  const session = await verifySession();

  const parsed = myPhoneSchema.safeParse({ phone: formData.get("phone") });
  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? "Invalid input" };
  }

  await db.user.update({
    where: { id: session.userId },
    data: { phone: parsed.data.phone ? normalizePhone(parsed.data.phone) : null },
  });

  revalidatePath("/settings");
  return { success: true };
}
